name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean directories and binaries
        run: |
          rm -rf frontend
          rm -rf reports_tmp
          rm -f backend/public/resumes/*.pdf
          rm -rf .github

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "deploy@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Deploy clean package" || exit 0
          git push https://Vetrii:$HF_TOKEN@huggingface.co/spaces/Vetrii/urscore-backend main --force
